### 1. Update Vehicle 1 Location (Your Vehicle)
# Replace the sessionId with a real one you got from Journey Service!
POST http://127.0.0.1:8090/api/v1/locations/update
Content-Type: application/json

{
  "sessionId": "f6ae570d-a562-40dc-8686-089874397eb3",
  "vehicleType": "car",
  "latitude": 22.5730,
  "longitude": 88.3770
}

###

### 2. Update Vehicle 2 Location (Nearby Vehicle - 500 meters away)
POST http://127.0.0.1:8090/api/v1/locations/update
Content-Type: application/json

{
  "sessionId": "f5ee8590-581c-4cdc-b9a6-8e03480e49fe",
  "vehicleType": "car",
  "latitude": 22.5750,
  "longitude": 88.3770
}

###

### 3. Stream Nearby Vehicles (The Radar)
# Open this and leave it running! It will stream updates every 2 seconds.
# We are centering the radar exactly on Vehicle 1's coordinates.
GET http://127.0.0.1:8090/api/v1/locations/nearby?sessionId=f6ae570d-a562-40dc-8686-089874397eb3
Accept: text/event-stream